# Generated by Django 5.1.5 on 2025-03-02 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_remove_application_company_application_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jobs.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='apply_date',
            field=models.DateField(),
        ),
    ]
