# Generated by Django 5.1.5 on 2025-03-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_application_company_alter_application_apply_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='apply_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
